OOP_P: generalAlert.o greenAlert.o yellowAlert.o redAlert.o FirstAlert.o main.cpp
	g++ -Wall -std=c++11 -o OOP_P main.cpp generalAlert.o greenAlert.o yellowAlert.o redAlert.o FirstAlert.o

generalAlert.o: generalAlert.h generalAlert.cpp
	g++ -Wall -std=c++11 -c generalAlert.cpp

yellowAlert.o: yellowAlert.h yellowAlert.cpp
	g++ -Wall -std=c++11 -c yellowAlert.cpp

greenAlert.o: greenAlert.h greenAlert.cpp
	g++ -Wall -std=c++11 -c greenAlert.cpp

redAlert.o: redAlert.h redAlert.cpp
	g++ -Wall -std=c++11 -c redAlert.cpp

FirstAlert.o: FirstAlert.h FirstAlert.cpp
	g++ -Wall -std=c++11 -c FirstAlert.cpp
